// Generated by CoffeeScript 1.6.3
(function($) {
  $.fn.waist = function(text, options) {
    var avg, family, font, height, randomstring, room, width;
    if (text == null) {
      text = null;
    }
    if (options == null) {
      options = {};
    }
    family = $("input").css("font-family") || 'Lucida Grande';
    text = text || this.text() || '';
    this.css("text-align", "center");
    options.min = options.min || 8;
    height = options.height || this.height() * 0.8 || 200;
    width = options.width || this.width() || 200;
    room = Math.floor(width / text.length);
    randomstring = "slkjeoclcmlsekjc";
    $("body").append("<span id=\"" + randomstring + "\" style=\"opacity:0.0; font-size:10px; font-family:" + family + ";\">" + text + "</span>");
    randomstring = "#" + randomstring;
    avg = Math.ceil($(randomstring).width() / text.length);
    $(randomstring).remove();
    font = Math.floor(room / (avg / 10));
    if (font > height) {
      font = height;
    }
    if (font < options.min) {
      font = options.min;
    }
    this.text(text);
    return this.css("font-size", parseInt(font));
  };
  return $.waist = function(options) {
    var sel;
    if (options == null) {
      options = {};
    }
    sel = options.sel || ".waist";
    return $(sel).each(function() {
      return $(this).waist(null, options);
    });
  };
})(jQuery);

/*
//@ sourceMappingURL=index.map
*/
