// Generated by CoffeeScript 1.6.3
$.fn.bar = function(data, options) {
  var already, colours, rect, stage, sum, svg, texts, x;
  if (data == null) {
    data = [];
  }
  if (options == null) {
    options = {
      w: 300,
      h: 30,
      delay: 0,
      duration: 800,
      ease: "linear",
      labels: true
    };
  }
  stage = this[0];
  colours = ["steelblue", "darkred", "#1f77b4", "#aec7e8", "#ff7f0e", "#ffbb78", "#2ca02c", "#98df8a", "#d62728", "#ff9896", "#9467bd", "#c5b0d5", "#8c564b", "#c49c94", "#e377c2", "#f7b6d2", "#7f7f7f", "#c7c7c7", "#bcbd22", "#dbdb8d", "#17becf", "#9edae5"];
  svg = d3.select(stage).append("svg:svg").attr("height", options.h).attr("width", options.w);
  sum = data.reduce((function(p, v) {
    return p + (v.value || 0);
  }), 0);
  x = d3.scale.linear().domain([0, sum]).range([0, options.w]);
  rect = svg.selectAll("rect").data(data).enter().append("rect");
  already = function(i) {
    if (i === 0) {
      0;
    }
    return data.slice(0, i).reduce((function(p, c) {
      return (parseInt(p) + c.value) || 0;
    }), 0);
  };
  rect.attr("x", function(d, i) {
    return 0;
  }).attr("y", function(d) {
    return 0;
  }).attr("height", options.h).attr("width", function(d) {
    return x(0);
  }).attr("fill-opacity", 1.0).attr("title", function(d, i) {
    return d.title || '';
  }).style("fill", function(d, i) {
    return d.color || colours[i];
  });
  rect.transition().duration(options.duration).ease(options.ease).delay(function(d, i) {
    return options.delay;
  }).attr("x", function(d, i) {
    return x(already(i));
  }).attr("width", function(d) {
    return x(d.value);
  });
  rect.append("svg:title").text(function(d, i) {
    return d.title || "";
  });
  if (options.labels) {
    texts = svg.selectAll("text").data(data).enter().append("text");
    return texts.style("fill", "white").style("font-size", "12").attr("x", function(d, i) {
      return 0;
    }).attr("y", function(d, i) {
      return options.h / 2;
    }).attr("text-anchor", "start").attr("dx", 10).transition().duration(options.duration).ease(options.ease).delay(function(d, i) {
      return options.delay;
    }).attr("x", function(d, i) {
      return x(already(i));
    }).text(function(d) {
      if (x(d.value) > 0) {
        return d.title || "";
      }
    });
  }
};

/*
//@ sourceMappingURL=index.map
*/
