// Generated by CoffeeScript 1.6.3
$(function() {
  var bang, cleanup, i, new_colour, new_transition, prepare_next;
  new_transition = function() {
    var i, transitions;
    transitions = [
      {
        left: 0,
        top: 100
      }, {
        left: 0,
        top: -100
      }, {
        left: 100,
        top: 0
      }, {
        left: -100,
        top: 0
      }
    ];
    i = Math.floor(Math.random() * transitions.length);
    return transitions[i];
  };
  new_colour = function() {
    var colours, i;
    colours = ["#1f77b4", "#aec7e8", "#ff7f0e", "#ffbb78", "#2ca02c", "#98df8a", "#d62728", "#ff9896", "#9467bd", "#c5b0d5", "#8c564b", "#c49c94", "#e377c2", "#f7b6d2", "#7f7f7f", "#c7c7c7", "#bcbd22", "#dbdb8d", "#17becf", "#9edae5"];
    i = Math.floor(Math.random() * colours.length);
    return colours[i];
  };
  i = 0;
  prepare_next = function() {
    var next, t;
    console.log("prepare");
    i++;
    t = new_transition();
    next = $("<span class=\"box next\"></span>");
    next.html(i);
    next.css("background", new_colour());
    next.css("left", "" + t.left + "%");
    next.css("top", "" + t.top + "%");
    return $("#stage").append(next);
  };
  cleanup = function() {
    console.log("cleanup");
    $(this).siblings(".current").remove();
    $(this).addClass("current");
    $(this).removeClass("next");
    $(this).siblings(".next").remove();
    return prepare_next();
  };
  bang = function() {
    console.log($(".next").length);
    return $(".next").animate({
      left: "0%",
      top: "0%"
    }, 400, "easeInExpo", cleanup);
  };
  prepare_next();
  return window.setInterval(function() {
    return bang();
  }, 2000);
});

/*
//@ sourceMappingURL=index.map
*/
