// Generated by CoffeeScript 1.6.3
$(function() {
  var cell, d3_category20, div, h, json, treemap, w;
  cell = function() {};
  this.style("left", function(d) {
    return d.x + "px";
  }).style("top", function(d) {
    return d.y + "px";
  }).style("width", function(d) {
    return d.dx - 1 + "px";
  }).style("height", function(d) {
    return d.dy - 1 + "px";
  });
  w = 960;
  h = 500;
  d3_category20 = ["#1f77b4", "#aec7e8", "#ff7f0e", "#ffbb78", "#2ca02c", "#98df8a", "#d62728", "#ff9896", "#9467bd", "#c5b0d5", "#8c564b", "#c49c94", "#e377c2", "#f7b6d2", "#7f7f7f", "#c7c7c7", "#bcbd22", "#dbdb8d", "#17becf", "#9edae5"];
  treemap = d3.layout.treemap().size([w, h]).sticky(true).value(function(d) {
    return d.size;
  });
  div = d3.select("#chart").append("div").style("position", "relative").style("width", w + "px").style("height", h + "px");
  json = {
    "name": "flare",
    "size": 50,
    "children": [
      {
        "name": "analytics",
        "children": [
          {
            "name": "cluster",
            "children": [
              {
                "name": "aa",
                "size": 138
              }, {
                "name": "ff",
                "size": 112
              }, {
                "name": "dd",
                "size": 143
              }
            ]
          }, {
            "name": "graph",
            "children": [
              {
                "name": "ccc",
                "size": 134
              }, {
                "name": "wwwww",
                "size": 131
              }
            ]
          }
        ]
      }, {
        "name": "asdf",
        "size": 134
      }
    ]
  };
  div.data([json]).selectAll("div").data(treemap.nodes).enter().append("div").attr("class", "cell").style("background", function(d, i) {
    if (!d.children) {
      return d3_category20[i];
    }
  }).data(treemap.value(function(d) {
    return 1;
  })).call(cell).text(function(d) {
    if (d.children) {
      return null;
    } else {
      return d.name;
    }
  });
  return div.selectAll("div").data(treemap.value(function(d) {
    return d.size;
  })).transition().duration(2500).call(cell);
});

/*
//@ sourceMappingURL=index.map
*/
