// Generated by CoffeeScript 1.6.3
$(function() {
  return $.fn.firebase = function() {
    var init, update, uuid;
    uuid = function(length) {
      var id;
      if (length == null) {
        length = 7;
      }
      id = "";
      while (id.length < length) {
        id += Math.random().toString(36).substr(2);
      }
      return "id" + id.substr(0, length);
    };
    init = function(account, namespace) {
      if (namespace == null) {
        namespace = uuid();
      }
      root.fb = new Firebase("http://" + account + ".firebaseio.com").child(namespace);
      return $(".mack").each(function(i, d) {
        var el, key;
        el = $(this);
        key = el.attr("id") || ("mackid" + i);
        el.attr("mack-id", key);
        el.val();
        el.focusout(function() {
          return update();
        });
        return root.fb.on("value", function(snapshot) {
          var obj;
          obj = snapshot.val() || {};
          return Object.keys(obj).forEach(function(key) {
            return $("input[mack-id=\"" + key + "\"]").val(obj[key]);
          });
        });
      });
    };
    update = function() {
      var obj;
      obj = {};
      $(".mack").each(function(i, d) {
        var el;
        el = $(this);
        return obj[el.attr("mack-id")] = el.val() || el.html();
      });
      return root.fb.set(obj);
    };
    return init();
  };
});
