// Generated by CoffeeScript 1.6.3
$(function() {
  var data, obj;
  $.fn.bar = function(data, options) {
    var stage;
    if (data == null) {
      data = {};
    }
    if (options == null) {
      options = {
        w: 300,
        h: 30,
        delay: 0,
        duration: 800,
        ease: "linear",
        labels: true
      };
    }
    stage = $(this);
    return window.r = new Ractive({
      el: stage,
      data: data,
      template: HAML.bar({})
    });
  };
  data = [
    {
      value: 25,
      title: "good",
      color: "steelblue"
    }, {
      value: 75,
      title: "evil",
      color: "darkred"
    }
  ];
  obj = {
    bars: data,
    w: 300,
    h: 30,
    scale: function(data) {
      var sum;
      return sum = data.reduce((function(p, v) {
        return p + (v.value || 0);
      }), 0);
    }
  };
  return $("#results").bar(obj);
});

/*
//@ sourceMappingURL=index.map
*/
