// Generated by CoffeeScript 1.6.3
$(function() {
  var o, polygon, square;
  o = {
    angle: 50,
    width: 200,
    overlap: 30,
    border: 85,
    topics: [
      {
        image: "https://www.googleapis.com/freebase/v1/image/en/toronto?mode=fillcropmid&maxwidth=300&maxheight=300",
        name: "toronto"
      }, {
        image: "https://www.googleapis.com/freebase/v1/image/en/vancouver?mode=fillcropmid&maxwidth=300&maxheight=300",
        name: "vancouver"
      }
    ]
  };
  $("#result").html(HAML.angler(o));
  square = function() {
    return "m 0 0\nl " + width + " 0\nl 0 " + width + "\nl " + (-width) + " 0\nz";
  };
  return polygon = function() {
    return "m " + (width - overlap) + " 0\nl " + width + " 0\nl 0 " + width + "\nl " + (-1 * (overlap * (-1 * (angle / 100))) - width) + " 0\nz";
  };
});

/*
//@ sourceMappingURL=index.map
*/
